DROP DATABASE If EXISTS mvp;

CREATE DATABASE mvp;

\c mvp;

DROP TABLE IF EXISTS live, pump;

CREATE TABLE live(
  id SERIAL PRIMARY KEY,
  baby_name VARCHAR(50) NOT NULL,
  time_fed VARCHAR(100) NOT NULL,
  side VARCHAR(50) NOT NULL,
  duration INT NOT NULL
);

CREATE TABLE pump(
  id SERIAL PRIMARY KEY,
  side VARCHAR(50) NOT NULL,
  time_pumped VARCHAR(100) NOT NULL,
  duration INT NOT NULL,
  amount DECIMAL NOT NULL,
  units VARCHAR(10) NOT NULL,
  storage VARCHAR(50) NOT NULL
);